const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const test = require('node:test');
const vm = require('node:vm');

test('root chrome exposes four tabs and keeps Network copy without Empire', () => {
  const html = fs.readFileSync(path.join(__dirname, '..', 'index.html'), 'utf8');
  assert.match(html, /role="tablist"/);
  assert.match(html, />Overview</);
  assert.match(html, />Location</);
  assert.match(html, />Process</);
  assert.match(html, />Economics</);
  assert.doesNotMatch(html, /empire/i);
  assert.match(html, /Network/);
  assert.match(html, /id="networkPanel"/);
  assert.doesNotMatch(html, /role="tab"[^>]*>\s*Network\s*</i);
  assert.match(html, /id="loadMethanolPlant"/);
  assert.match(html, /id="overviewYield"/);
  assert.match(html, /cases\/methanol\.js/);
  assert.ok(html.indexOf('data/atacama-pacific-seawater.js') < html.indexOf('cases/methanol.js'));
  assert.ok(html.indexOf('data/dead-sea-brine.js') < html.indexOf('data/persian-gulf-sabkha-brine.js'));
  assert.ok(html.indexOf('data/persian-gulf-sabkha-brine.js') < html.indexOf('data/site-assays.js'));
  assert.ok(html.indexOf('data/atacama-lithium-brine.js') < html.indexOf('data/site-assays.js'));
  assert.ok(html.indexOf('data/lake-mackay-wa-brine.js') < html.indexOf('data/site-assays.js'));
  assert.ok(html.indexOf('data/great-salt-lake-brine.js') < html.indexOf('data/site-assays.js'));
  assert.ok(html.indexOf('data/salton-sea-brine.js') < html.indexOf('data/site-assays.js'));
  assert.ok(html.indexOf('data/red-sea-sabkha-brine.js') < html.indexOf('data/site-assays.js'));
  assert.ok(html.indexOf('data/kutch-subsoil-brine.js') < html.indexOf('data/site-assays.js'));
  assert.ok(html.indexOf('data/texas-gulf-desal-brine.js') < html.indexOf('data/site-assays.js'));
  assert.ok(html.indexOf('data/mediterranean-swro-brine.js') < html.indexOf('data/site-assays.js'));
  assert.ok(html.indexOf('data/arabian-sea-seawater.js') < html.indexOf('data/site-assays.js'));
  assert.ok(html.indexOf('data/gulf-of-kutch-seawater.js') < html.indexOf('data/site-assays.js'));
  assert.ok(html.indexOf('data/benguela-atlantic-seawater.js') < html.indexOf('data/site-assays.js'));
  assert.match(html, /id="sitePreset"/);
  assert.match(html, /id="siteMapLegend"/);
  assert.match(html, /data\/site-presets\.js/);
  assert.match(html, /vendor\/LercDecode\.js/);
  assert.ok(html.indexOf('data/site-presets.js') < html.indexOf('js/flowsheet-app.js'));
  assert.match(html, /data\/tea-screening\.js/);
  assert.ok(html.indexOf('data/tea-screening.js') < html.indexOf('cases/abundance.js'));
  assert.ok(html.indexOf('data/tea-screening.js') < html.indexOf('cases/sabatier.js'));
  assert.ok(html.indexOf('vendor/LercDecode.js') < html.indexOf('js/flowsheet-app.js'));
  assert.match(html, /engine\/site-search\.js/);
  assert.ok(html.indexOf('cases/network.js') < html.indexOf('engine/site-search.js'));
  assert.ok(html.indexOf('engine/site-search.js') < html.indexOf('js/flowsheet-app.js'));
});
